name: GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    permissions:
      contents: write        

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_HOST: https://www.ppos.top
          VITE_CLIENT_ID: 66770019f90670c913af

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: weibo
          path: ./dist
          retention-days: 1
          if-no-files-found: error

  deploy_remote:
    runs-on: ubuntu-latest
    environment: github-pages
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: weibo
          path: ./dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ssh.key
          chmod 600 ~/.ssh/ssh.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/ssh.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: delete dist
        run: ssh production 'cd weibo-docker && tar -zcf dist.tar.gz dist --remove-files'

      - name: copy dist
        if: ${{ failure() }}
        run: |
          scp -r ./dist production:~/weibo-docker
          ssh production 'cd ~/weibo-docker && sudo docker-compose restart nginx'

  deploy_gh:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: weibo

      - name: Display structure of downloaded files
        run: ls -R

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: Deploy_gh
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true